create table tarot_spreads
(
    id                bigint auto_increment
        primary key,
    name              varchar(255)                        not null,
    spread_type       enum ('basic', 'advanced')          not null,
    is_paid           bit       default b'0'              not null,
    is_popular        bit       default b'0'              not null,
    tags              varchar(255)                        null,
    test_count        bigint    default 0                 null,
    like_count        bigint    default 0                 null,
    image_large       varchar(255)                        null,
    image_small       varchar(255)                        null,
    description       text                                null,
    related_questions text                                null,
    created_at        timestamp default CURRENT_TIMESTAMP null,
    updated_at        timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP
);

INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (1, '三牌阵', 'basic', false, true, 'general,outcome', 100, 50, null, null, '通过过去、现在、未来的角度解读问题', null, '2024-10-01 12:44:02', '2024-10-01 12:44:02');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (2, '三牌阵', 'basic', false, true, 'general,outcome', 1500, 300, null, null, '通过过去、现在、未来的角度解读问题', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (3, '单牌阵', 'basic', false, false, 'general', 2000, 400, null, null, '快速回答特定问题的一张牌解读', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (4, '十字架牌阵', 'advanced', true, true, 'general,event,outcome', 1200, 450, null, null, '深入解析问题的多个方面，帮助用户获得全面的理解', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (5, '关系牌阵', 'basic', false, true, 'relationship', 1800, 350, null, null, '用于分析人际关系中的潜在问题和发展方向', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (6, '七牌阵', 'advanced', true, true, 'general,outcome', 800, 220, null, null, '通过七张牌的方式详细解析用户的问题和事件发展', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (7, '爱情三角牌阵', 'basic', false, true, 'relationship,outcome', 1000, 500, null, null, '帮助用户分析三角恋中的关键问题', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (8, '财富牌阵', 'basic', false, false, 'wealth', 1300, 330, null, null, '用于解读用户的财富状况和财务发展方向', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (9, '事业发展牌阵', 'advanced', true, true, 'career,outcome', 900, 250, null, null, '结合用户的职业发展，提供深度的事业机遇与挑战分析', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (10, '决策牌阵', 'basic', false, true, 'decision,outcome', 1100, 300, null, null, '帮助用户做出重要决策的简单三张牌阵', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (11, '人生之路牌阵', 'advanced', true, false, 'event,growth', 700, 190, null, null, '分析用户未来的关键人生阶段和潜在发展方向', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (12, '复合机会牌阵', 'basic', false, false, 'relationship,outcome', 900, 320, null, null, '针对感情中的复合问题，提供机会与建议', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (13, '命运之轮牌阵', 'advanced', true, true, 'fate,event', 800, 260, null, null, '从命运角度出发，分析人生中的关键转折点', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (14, '幸运牌阵', 'basic', false, true, 'general,outcome', 1600, 400, null, null, '快速解读当天的幸运运势', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (15, '灵魂伙伴牌阵', 'advanced', true, true, 'relationship', 500, 180, null, null, '帮助用户找到与自己灵魂契合的伙伴', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (16, '问题解答牌阵', 'basic', false, false, 'event,outcome', 1900, 410, null, null, '针对用户提出的具体问题，提供快速解答', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (17, '事件发展牌阵', 'basic', false, true, 'event', 1700, 390, null, null, '通过三张牌分析事件的过去、现在和未来', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (18, '感情分析牌阵', 'advanced', true, false, 'relationship,event', 1000, 340, null, null, '深度解读用户的感情状态和潜在发展', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (19, '健康牌阵', 'basic', false, false, 'health,general', 1400, 360, null, null, '用于解读用户的健康状况和未来健康发展', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (20, '成长牌阵', 'advanced', true, false, 'growth', 600, 200, null, null, '帮助用户识别个人成长中的关键挑战和机遇', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
INSERT INTO blog.tarot_spreads (id, name, spread_type, is_paid, is_popular, tags, test_count, like_count, image_large, image_small, description, related_questions, created_at, updated_at) VALUES (21, '转折点牌阵', 'advanced', true, true, 'event,general', 700, 210, null, null, '用于分析人生中的关键转折点和未来的发展方向', null, '2024-10-01 12:45:30', '2024-10-01 12:45:30');
